version: '3.8'

services:
  postgres:
    container_name: postgres
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user1'
      - 'TIME_ZONE=UTC'
    ports:
      - '5436:5432'
    volumes:
      - db:/data/db
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true

  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"

#  elasticsearch:
#    image: elasticsearch:8.8.0
#    container_name: elasticsearch
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      - bootstrap.memory_lock=true
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#      - ELASTIC_PASSWORD=password
#      - xpack.security.enabled=true
#    networks:
#      - logging-network
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.8.0
#    container_name: logstash
#    depends_on:
#      - elasticsearch
#    ports:
#      - "9999:9999"
#    volumes:
#      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    networks:
#      - logging-network
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.8.0
#    container_name: kibana
#    depends_on:
#      - logstash
#      - elasticsearch
#    ports:
#      - "5601:5601"
#    networks:
#      - logging-network
#    environment:
#      - ELASTIC_PASSWORD=password
#      - ELASTICSEARCH_USERNAME=elastic
#
#networks:
#  logging-network:
#    driver: bridge

volumes:
  db:
    driver:
      local