version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5436:5432'
    volumes:
      - db:/data/db
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true

volumes:
  db:
    driver:
      local