version: '3.8'

services:
  postgres:
    container_name: postgres
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user1'
      - 'TIME_ZONE=UTC'
    ports:
      - '5436:5432'
    volumes:
      - db:/data/db
    labels:
      org.springframework.boot.readiness-check.tcp.disable: true

#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#
  activemq:
    image: webcenter/activemq:latest
    container_name: activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    ports:
      - "61616:61616"
      - "8161:8161"

volumes:
  db:
    driver:
      local