version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
      - 'TIME_ZONE=UTC'
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    ports:
      - '9000:8000'
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/database
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password
    links:
      - postgres

volumes:
  db:
    driver:
        local