spring:
  application:
    name: faculty

  profiles:
    active: dev

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true

---
spring:
  config:
    import:
      - file:.env[.properties]
      - configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: never


activemq:
  faculty:
    queue:
      name: "faculty_service"
    delete: "faculty_delete_service"
    get: "faculty_get_service"
    routing:
      key: "faculty_service_routing_key"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

server:
  port: 8001




