spring:
  application:
    name: faculty

  profiles:
    active: dev

  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true

activemq:
  faculty:
    queue:
      name: "faculty_service"
    delete: "faculty_delete_service"
    get: "faculty_get_service"
    routing:
      key: "faculty_service_routing_key"

---
spring:
  config:
    import:
      - file:.env[.properties]
      - configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev
allowed:
  origins: '*'

---
spring:
  config:
    import:
      - configserver:${CONFIG_URL}
    activate:
      on-profile: docker
allowed:
  origins: http://${GATEWAY_HOST}:${GATEWAY_PORT}