spring:
  application:
    name: gateway

  profiles:
    active: dev

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
---
spring:
  config:
    import:
      - configserver:${CONFIG_URL}
    activate:
      on-profile: docker