spring:
  application:
    name: gateway

  profiles:
    active: dev

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

---
spring:
  config:
    import:
      - configserver:${CONFIG_URL}
    activate:
      on-profile: docker
---
service:
  uri:
    faculty: "http://localhost:${FACULTY_SERVICE_PORT}"
    discipline: "http://localhost:${FACULTY_SERVICE_PORT}"
    schedule: "http://localhost:${FACULTY_SERVICE_PORT}"
    auth: "http://localhost:${USER_SERVICE_PORT}"
    user: "http://localhost:${USER_SERVICE_PORT}"
    enrollment: "http://localhost:${ENROLLMENT_SERVICE_PORT}"
    notification: "http://localhost:${NOTIFICATION_SERVICE_PORT}"
    admin: "http://localhost:${ADMIN_SERVICE_PORT}"
spring:
  config:
    import:
      - file:.env[.properties]
      - configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev