# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: app
          image: stasbukovskyi/user-service:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres/database
          imagePullPolicy: Always

---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer