spring:
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
       mode: always
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
service:
  auth:
    base-url: 'http://localhost:8080/api/v1/auth'
activemq:
  faculty:
    queue:
      name: "faculty_service"
    routing:
      key: "faculty_service_routing_key"
server:
  port: 8001




