spring:
  application:
    name: "faculty_service"
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true

---
spring:
  config:
    import: configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: never
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    topic-name: "faculty_service"
  datasource:
    url: jdbc:postgresql://127.0.0.1:5436/database
    username: user1
    password: password
service:
  auth:
    base-url: 'http://localhost:8080/api/v1/auth'
activemq:
  faculty:
    queue:
      name: "faculty_service"
    delete: "faculty_delete_service"
    get: "faculty_get_service"
    routing:
      key: "faculty_service_routing_key"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

server:
  port: 8001




