spring:
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: true

service:
  auth:
    base-url: 'http://localhost:8080/api/v1/auth'

server:
  port: 8001


