spring:
  application:
    name: auth

  profiles:
    active: dev

  docker:
    compose:
      enabled: false

  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

token:
  signing:
    key: ahtyiY4ky67ovr68w8846Gr67Ggf6HhfnkOPnsodosaOPAwpmwqppmcsa01242dpwsazk
  expiration: 4320000ms

---
spring:
  config:
    import:
      - file:.env[.properties]
      - configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev
allowed:
  origins: *

---
spring:
  config:
    import:
      - configserver:${CONFIG_URL}
    activate:
      on-profile: docker
allowed:
  origins: http://${GATEWAY_HOST}:${GATEWAY_PORT}