spring:
  application:
    name: analytics

  profiles:
    active: dev

  main:
    allow-bean-definition-overriding: true

---
spring:
  config:
    import:
      - file:.env[.properties]
      - configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev

---
spring:
  config:
    import:
      - configserver:${CONFIG_URL}
    activate:
      on-profile: docker

activemq:
  faculty:
    queue:
      name: "faculty_service"
    delete: "faculty_delete_service"
    get: "faculty_get_service"
    routing:
      key: "faculty_service_routing_key"
