spring:
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  application:
    name: user-service

  main:
    allow-bean-definition-overriding: true
token:
  signing:
    key: ahtyiY4ky67ovr68w8846Gr67Ggf6HhfnkOPnsodosaOPAwpmwqppmcsa01242dpwsazk
  expiration: 4320000ms

---
spring:
  config:
    import: configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
