spring:
  boot:
    admin:
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true
server:
  port: 8002

logging:
  file:
    path: /home/stas/projects/spring-boot-microservices/logs/spring-boot-microservices.log
    name: spring-boot-microservices.log