spring:
  boot:
    admin:
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true
server:
  port: 8002

logging:
  file:
    path: C:/Users/Nazar/IdeaProjects/SpringBoot_2y/microservices/spring-boot-microservices/logs
    name : spring-boot-microservices.log