spring:
  boot:
    admin:
      context-path: /admin
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
server:
  port: 8002

---
spring:
  application:
    name: admin-service
  config:
    import: configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev
