spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
activemq:
  faculty:
    queue:
      name: "faculty_service"
    delete: "faculty_delete_service"
    routing:
      key: "faculty_service_routing_key"
server:
  port: 8005




