spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
activemq:
  faculty:
    queue:
      name: "faculty_service"
    delete: "faculty_delete_service"
    get: "faculty_get_service"
    routing:
      key: "faculty_service_routing_key"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true
server:
  port: 8005




