spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  boot:
    admin:
      client:
        url: "http://localhost:8002/admin"
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: "analytics-service"
    
activemq:
  faculty:
    queue:
      name: "faculty_service"
    delete: "faculty_delete_service"
    get: "faculty_get_service"
    routing:
      key: "faculty_service_routing_key"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
    shutdown:
      enabled: true
      
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"
server:
  port: 8005

---
spring:
  application:
    name: analytics-service
  config:
    import: configserver:http://root:s3cr3t@localhost:8888
    activate:
      on-profile: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin